apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-todo
spec:
  schedule: "0 * * * *"  # each hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-todo-container
            image: daily-todo:1.1
            env:
            - name: ADD_TODO_URL
              value: "http://todo-backend-svc:2351"
          restartPolicy: OnFailure
            