apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
        - name: shared-pingpong-image
          persistentVolumeClaim:
            claimName: ping-pong-pv-claim
      containers:
        - name: read-log
          image: read-log:1.5
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/log/
          - name: shared-pingpong-image
            mountPath: /usr/log/pingpong/
        - name: write-log
          image: write-log:1.1
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/log/
